import { Box, Flex, Heading, Image, Text, Wrap, WrapItem } from "@chakra-ui/react";

export function Cities() {
  return (
    <Box
      mt="20"
    >
      <Heading
        mb="10"
      >
        Cidades +100
      </Heading>
      <Wrap
        spacing="15px"
      >
        <WrapItem
          flexDirection="column"
          bg="light.900"
          w="256px"
          h="279px"
          borderRadius="4px"
        >
          <Image 
            src="https://images.unsplash.com/photo-1587726480710-003743795e40?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bG9uZG9ufGVufDB8MnwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
            alt="Londres"
            w="256px"
            h="173px"
            borderTopRadius="4px"
          />
          <Flex
            w="100%"
            h="100%"
            px="6"
            py="18px"
            justify="space-between"
            alignItems="center"
            borderBottomRadius="4px"
            borderBottom="1px solid #FFBA08"
            borderX="1px solid #FFBA08"
          >
            <Flex
              direction="column"
            >
              <Text
                as="span"
                fontWeight="600"
                fontSize="20px"
                lineHeight="25px"
              >
                Londres
              </Text>
              <Text 
                as="span"
                color="dark.400"
                fontWeight="500"
                fontSize="16px"
                lineHeight="26px"
              >
                Reino Unido
              </Text>
            </Flex>
            <Text 
              as="span"
              bg="url(https://www.countryflags.io/gb/flat/64.png)"
              bgSize="fill"
              bgPosition="center"
              w="30px"
              h="30px"
              borderRadius="50%"
            />
          </Flex>
        </WrapItem>
        <WrapItem
          flexDirection="column"
          bg="light.900"
          w="256px"
          h="279px"
          borderRadius="4px"
        >
          <Image 
            src="https://images.unsplash.com/photo-1587726480710-003743795e40?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bG9uZG9ufGVufDB8MnwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
            alt="Londres"
            w="256px"
            h="173px"
            borderTopRadius="4px"
          />
          <Flex
            w="100%"
            h="100%"
            px="6"
            py="18px"
            justify="space-between"
            alignItems="center"
            borderBottomRadius="4px"
            borderBottom="1px solid #FFBA08"
            borderX="1px solid #FFBA08"
          >
            <Flex
              direction="column"
            >
              <Text
                as="span"
                fontWeight="600"
                fontSize="20px"
                lineHeight="25px"
              >
                Londres
              </Text>
              <Text 
                as="span"
                color="dark.400"
                fontWeight="500"
                fontSize="16px"
                lineHeight="26px"
              >
                Reino Unido
              </Text>
            </Flex>
            <Text 
              as="span"
              bg="url(https://www.countryflags.io/gb/flat/64.png)"
              bgSize="fill"
              bgPosition="center"
              w="30px"
              h="30px"
              borderRadius="50%"
            />
          </Flex>
        </WrapItem>
        <WrapItem
          flexDirection="column"
          bg="light.900"
          w="256px"
          h="279px"
          borderRadius="4px"
        >
          <Image 
            src="https://images.unsplash.com/photo-1587726480710-003743795e40?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bG9uZG9ufGVufDB8MnwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
            alt="Londres"
            w="256px"
            h="173px"
            borderTopRadius="4px"
          />
          <Flex
            w="100%"
            h="100%"
            px="6"
            py="18px"
            justify="space-between"
            alignItems="center"
            borderBottomRadius="4px"
            borderBottom="1px solid #FFBA08"
            borderX="1px solid #FFBA08"
          >
            <Flex
              direction="column"
            >
              <Text
                as="span"
                fontWeight="600"
                fontSize="20px"
                lineHeight="25px"
              >
                Londres
              </Text>
              <Text 
                as="span"
                color="dark.400"
                fontWeight="500"
                fontSize="16px"
                lineHeight="26px"
              >
                Reino Unido
              </Text>
            </Flex>
            <Text 
              as="span"
              bg="url(https://www.countryflags.io/gb/flat/64.png)"
              bgSize="fill"
              bgPosition="center"
              w="30px"
              h="30px"
              borderRadius="50%"
            />
          </Flex>
        </WrapItem>
        <WrapItem
          flexDirection="column"
          bg="light.900"
          w="256px"
          h="279px"
          borderRadius="4px"
        >
          <Image 
            src="https://images.unsplash.com/photo-1587726480710-003743795e40?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bG9uZG9ufGVufDB8MnwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
            alt="Londres"
            w="256px"
            h="173px"
            borderTopRadius="4px"
          />
          <Flex
            w="100%"
            h="100%"
            px="6"
            py="18px"
            justify="space-between"
            alignItems="center"
            borderBottomRadius="4px"
            borderBottom="1px solid #FFBA08"
            borderX="1px solid #FFBA08"
          >
            <Flex
              direction="column"
            >
              <Text
                as="span"
                fontWeight="600"
                fontSize="20px"
                lineHeight="25px"
              >
                Londres
              </Text>
              <Text 
                as="span"
                color="dark.400"
                fontWeight="500"
                fontSize="16px"
                lineHeight="26px"
              >
                Reino Unido
              </Text>
            </Flex>
            <Text 
              as="span"
              bg="url(https://www.countryflags.io/gb/flat/64.png)"
              bgSize="fill"
              bgPosition="center"
              w="30px"
              h="30px"
              borderRadius="50%"
            />
          </Flex>
        </WrapItem>
        <WrapItem
          flexDirection="column"
          bg="light.900"
          w="256px"
          h="279px"
          borderRadius="4px"
        >
          <Image 
            src="https://images.unsplash.com/photo-1587726480710-003743795e40?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bG9uZG9ufGVufDB8MnwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
            alt="Londres"
            w="256px"
            h="173px"
            borderTopRadius="4px"
          />
          <Flex
            w="100%"
            h="100%"
            px="6"
            py="18px"
            justify="space-between"
            alignItems="center"
            borderBottomRadius="4px"
            borderBottom="1px solid #FFBA08"
            borderX="1px solid #FFBA08"
          >
            <Flex
              direction="column"
            >
              <Text
                as="span"
                fontWeight="600"
                fontSize="20px"
                lineHeight="25px"
              >
                Londres
              </Text>
              <Text 
                as="span"
                color="dark.400"
                fontWeight="500"
                fontSize="16px"
                lineHeight="26px"
              >
                Reino Unido
              </Text>
            </Flex>
            <Text 
              as="span"
              bg="url(https://www.countryflags.io/gb/flat/64.png)"
              bgSize="fill"
              bgPosition="center"
              w="30px"
              h="30px"
              borderRadius="50%"
            />
          </Flex>
        </WrapItem>
      </Wrap>
    </Box>
  );
}