import { Flex, Image, Text } from "@chakra-ui/react";

export function TravelTypes() {
  return (
    <Flex
      as="section"
      w="1160"
      my="20"
      mx="10"
      justify="space-between"
    >
      <Flex
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        <Image
          h="85px"
          w="85px"
          src="/images/cocktail.svg" 
          alt="Vida noturna"
        />
        <Text
          fontWeight="semibold"
          fontSize="24px"
          color="dark.700"
        >
          vida noturna
        </Text>
      </Flex>
      <Flex
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        <Image
          h="85px"
          w="85px"
          src="/images/surf.svg" 
          alt="Praia"
        />
        <Text
          fontWeight="semibold"
          fontSize="24px"
          color="dark.700"
        >
          praia
        </Text>
      </Flex>
      <Flex
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        <Image
          h="85px"
          w="85px"
          src="/images/building.svg" 
          alt="Moderno"
        />
        <Text
          fontWeight="semibold"
          fontSize="24px"
          color="dark.700"
        >
          moderno
        </Text>
      </Flex>
      <Flex
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        <Image
          h="85px"
          w="85px"
          src="/images/museum.svg" 
          alt="Clássico"
        />
        <Text
          fontWeight="semibold"
          fontSize="24px"
          color="dark.700"
        >
          clássico
        </Text>
      </Flex>
      <Flex
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        <Image
          h="85px"
          w="85px"
          src="/images/earth.svg" 
          alt="Mais"
        />
        <Text
          fontWeight="semibold"
          fontSize="24px"
          color="dark.700"
        >
          e mais
        ...</Text>
      </Flex>
    </Flex>
  );
}